[project]
name = "magic-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.6.1",
    "python-dotenv>=1.1.1",
    "litellm>=1.30.7",
    "pydantic>=2.11.7",
]
