
scenario_evaluator_task:
  description: >
    Research and find cool things to do with the mentioned storage location.
    Focus on activities and events like download and upload.

  expected_output: >
    A list of recommended activities and events to interact with the storage location.
